query getCourses($lastCourse: String) {
  getCourses(lastCourse: $lastCourse) {
    ... on GetCourses {
      courses {
        id
        path
        title
        description
        area
        difficult
        photoURL
        videoURL
        thumbnailURL
        gifURL
        videoPlaybackID
        videoAssetId
        typeContent
        viewsCount
        clapsCount
        clapped
        claps
        commentsCount
        comments {
          id
          owner
          description
        }
        owner
        ownerProfile {
          uid
          displayName
          thumbnailURL
          photoURL
          profission
        }
        createdAt
        state
      }
      success {
        message
      }
    }
    ... on ErrorResponse {
      error {
        type
        message
      }
    }
  }
}
