query getCoursesByPath($path: String!, $lastCourse: String) {
  getCoursesByPath(path: $path, lastCourse: $lastCourse) {
    ... on GetCoursesByPath {
      coursesByPath {
        id
        path
        title
        description
        area
        difficult
        photoURL
        typeContent
        viewsCount
        clapsCount
        commentsCount
        comments {
          id
          owner
          description
        }
        owner
        ownerProfile {
          displayName
          photoURL
          thumbnailURL
          profission
        }
        createdAt
      }
      success {
        message
      }
    }
    ... on ErrorResponse {
      error {
        message
      }
    }
  }
}
