query getCommentByPost($post: String!) {
  getCommentByPost(post: $post) {
    ... on GetComment {
      comments {
        id
        owner
        description
        ownerProfile {
          uid
          displayName
          thumbnailURL
          profission
        }
        createdAt
      }
    }
    ... on ErrorResponse {
      error {
        type
        message
      }
    }
  }
}
