query getCoursesByUser($uid: String, $lastCourse: String) {
  getCoursesByUser(uid: $uid, lastCourse: $lastCourse) {
    ... on GetCoursesByOwner {
      coursesByOwner {
        id
        path
        owner
        title
        description
        area
        difficult
        photoURL
        videoURL
        thumbnailURL
        gifURL
        videoPlaybackID
        videoAssetId
        typeContent
        viewsCount
        clapsCount
        clapped
        claps
        commentsCount
        comments {
          id
          owner
          description
        }
        ownerProfile {
          uid
          displayName
          thumbnailURL
          photoURL
          profission
        }
        state
        createdAt
      }
      success {
        message
      }
    }
    ... on ErrorResponse {
      error {
        message
      }
    }
  }
}
