query getPostsByOwner($lastPost: String, $owner: String) {
  getPostsByOwner(lastPost: $lastPost, owner: $owner) {
    ... on GetPostsOwner {
      allPostOwner {
        id
        owner
        ownerProfile {
          displayName
          thumbnailURL
          profission
        }
        title
        description
        claps
        clapsCount
        commentsCount
        createdAt
        photoURL
      }
      success {
        message
      }
    }
    ... on ErrorResponse {
      error {
        type
        message
      }
    }
  }
}
