export enum EIcons {
  'guup',
  'guupLarge',
  'explorer',
  'news',
  'box',
  'profile',
  'search',
  'heart',
  'arrow',
  'dots',
  'chat',
  'project',
  'forum',
  'clock',
  'module',
  'chevron',
  'chevronMenu',
  'video',
  'article',
  'claps',
  'clapsActive',
  'bell',
  'save',
  'gallery',
  'lock',
  'unlock',
  'plus',
  'settings',
  'trash',
  'alert',
  'back',
}

export enum ETabIcon {
  'GuupExplorer' = 'explorer',
  'GuupExplorerFocus' = 'explorerFilled',
  'GuupNews' = 'news',
  'GuupNewsFocus' = 'newsFilled',
  'GuupCourse' = 'box',
  'GuupAccount' = 'profile',
  'GuupAccountFocus' = 'profileFilled',
}
